package com.ai.phoneagent

object AppPackageMapping {

    private fun normalize(s: String): String {
        return s.trim().lowercase().replace("\\s+".toRegex(), "").replace("-", "")
    }

    private val raw: Map<String, String> =
            mapOf(
                    // ===== 中文应用 =====
                    "微信" to "com.tencent.mm",
                    "QQ" to "com.tencent.mobileqq",
                    "微博" to "com.sina.weibo",
                    "新浪微博" to "com.sina.weibo",
                    "淘宝" to "com.taobao.taobao",
                    "天猫" to "com.tmall.wireless",
                    "京东" to "com.jingdong.app.mall",
                    "拼多多" to "com.xunmeng.pinduoduo",
                    "淘宝闪购" to "com.taobao.taobao",
                    "京东秒送" to "com.jingdong.app.mall",
                    "小红书" to "com.xingin.xhs",
                    "豆瓣" to "com.douban.frodo",
                    "知乎" to "com.zhihu.android",
                    "贴吧" to "com.baidu.tieba",
                    "高德地图" to "com.autonavi.minimap",
                    "百度地图" to "com.baidu.BaiduMap",
                    "美团" to "com.sankuai.meituan",
                    "大众点评" to "com.dianping.v1",
                    "饿了么" to "me.ele",
                    "肯德基" to "com.yek.android.kfc.activitys",
                    "携程" to "ctrip.android.view",
                    "铁路12306" to "com.MobileTicket",
                    "12306" to "com.MobileTicket",
                    "去哪儿" to "com.Qunar",
                    "去哪儿旅行" to "com.Qunar",
                    "航旅纵横" to "com.umetrip.android.msky.app",
                    "航旅" to "com.umetrip.android.msky.app",
                    "umetrip" to "com.umetrip.android.msky.app",
                    "Umetrip" to "com.umetrip.android.msky.app",
                    "滴滴出行" to "com.sdu.didi.psnger",
                    "bilibili" to "tv.danmaku.bili",
                    "抖音" to "com.ss.android.ugc.aweme",
                    "快手" to "com.smile.gifmaker",
                    "腾讯视频" to "com.tencent.qqlive",
                    "爱奇艺" to "com.qiyi.video",
                    "优酷视频" to "com.youku.phone",
                    "芒果TV" to "com.hunantv.imgo.activity",
                    "红果短剧" to "com.phoenix.read",
                    "网易云音乐" to "com.netease.cloudmusic",
                    "QQ音乐" to "com.tencent.qqmusic",
                    "汽水音乐" to "com.luna.music",
                    "喜马拉雅" to "com.ximalaya.ting.android",
                    "番茄小说" to "com.dragon.read",
                    "番茄免费小说" to "com.dragon.read",
                    "七猫免费小说" to "com.kmxs.reader",
                    "飞书" to "com.ss.android.lark",
                    "QQ邮箱" to "com.tencent.androidqqmail",
                    "豆包" to "com.larus.nova",
                    "keep" to "com.gotokeep.keep",
                    "美柚" to "com.lingan.seeyou",
                    "腾讯新闻" to "com.tencent.news",
                    "今日头条" to "com.ss.android.article.news",
                    "贝壳找房" to "com.lianjia.beike",
                    "安居客" to "com.anjuke.android.app",
                    "同花顺" to "com.hexin.plat.android",
                    "星穹铁道" to "com.miHoYo.hkrpg",
                    "崩坏：星穹铁道" to "com.miHoYo.hkrpg",
                    "恋与深空" to "com.papegames.lysk.cn",
                    "支付宝" to "com.eg.android.AlipayGphone",
                            "医院挂号通" to "com.guahao001.proj.yygh_app",
                            "医院挂号网" to "dtys.guahaowang",
                            // ===== Android系统设置 =====
                    "AndroidSystemSettings" to "com.android.settings",
                    "Android System Settings" to "com.android.settings",
                    "Android  System Settings" to "com.android.settings",
                    "Android-System-Settings" to "com.android.settings",
                    "Settings" to "com.android.settings",
                    
                    // ===== Android系统工具 =====
                    "AudioRecorder" to "com.android.soundrecorder",
                    "audiorecorder" to "com.android.soundrecorder",
                    "Chrome" to "com.android.chrome",
                    "chrome" to "com.android.chrome",
                    "Google Chrome" to "com.android.chrome",
                    "Clock" to "com.android.deskclock",
                    "clock" to "com.android.deskclock",
                    "Contacts" to "com.android.contacts",
                    "contacts" to "com.android.contacts",
                    "Files" to "com.android.fileexplorer",
                    "files" to "com.android.fileexplorer",
                    "File Manager" to "com.android.fileexplorer",
                    "file manager" to "com.android.fileexplorer",
                    // ===== Google生态和国际应用 =====
                    "gmail" to "com.google.android.gm",
                    "Gmail" to "com.google.android.gm",
                    "GoogleMail" to "com.google.android.gm",
                    "Google Mail" to "com.google.android.gm",
                    "GoogleFiles" to "com.google.android.apps.nbu.files",
                    "googlefiles" to "com.google.android.apps.nbu.files",
                    "FilesbyGoogle" to "com.google.android.apps.nbu.files",
                    "GoogleCalendar" to "com.google.android.calendar",
                    "GoogleCalendar" to "com.google.android.calendar",
                    "Google-Calendar" to "com.google.android.calendar",
                    "Google Calendar" to "com.google.android.calendar",
                    "google-calendar" to "com.google.android.calendar",
                    "google calendar" to "com.google.android.calendar",
                    "GoogleChat" to "com.google.android.apps.dynamite",
                    "Google Chat" to "com.google.android.apps.dynamite",
                    "Google-Chat" to "com.google.android.apps.dynamite",
                    "GoogleClock" to "com.google.android.deskclock",
                    "Google Clock" to "com.google.android.deskclock",
                    "Google-Clock" to "com.google.android.deskclock",
                    "GoogleContacts" to "com.google.android.contacts",
                    "Google-Contacts" to "com.google.android.contacts",
                    "Google Contacts" to "com.google.android.contacts",
                    "google-contacts" to "com.google.android.contacts",
                    "google contacts" to "com.google.android.contacts",
                    "GoogleDocs" to "com.google.android.apps.docs.editors.docs",
                    "Google Docs" to "com.google.android.apps.docs.editors.docs",
                    "googledocs" to "com.google.android.apps.docs.editors.docs",
                    "google docs" to "com.google.android.apps.docs.editors.docs",
                    "Google Drive" to "com.google.android.apps.docs",
                    "Google-Drive" to "com.google.android.apps.docs",
                    "google drive" to "com.google.android.apps.docs",
                    "google-drive" to "com.google.android.apps.docs",
                    "GoogleDrive" to "com.google.android.apps.docs",
                    "Googledrive" to "com.google.android.apps.docs",
                    "googledrive" to "com.google.android.apps.docs",
                    "GoogleFit" to "com.google.android.apps.fitness",
                    "googlefit" to "com.google.android.apps.fitness",
                    "GoogleKeep" to "com.google.android.keep",
                    "googlekeep" to "com.google.android.keep",
                    "GoogleMaps" to "com.google.android.apps.maps",
                    "Google Maps" to "com.google.android.apps.maps",
                    "googlemaps" to "com.google.android.apps.maps",
                    "google maps" to "com.google.android.apps.maps",
                    "Google Play Books" to "com.google.android.apps.books",
                    "Google-Play-Books" to "com.google.android.apps.books",
                    "google play books" to "com.google.android.apps.books",
                    "google-play-books" to "com.google.android.apps.books",
                    "GooglePlayBooks" to "com.google.android.apps.books",
                    "googleplaybooks" to "com.google.android.apps.books",
                    "GooglePlayStore" to "com.android.vending",
                    "Google Play Store" to "com.android.vending",
                    "Google-Play-Store" to "com.android.vending",
                    "GoogleSlides" to "com.google.android.apps.docs.editors.slides",
                    "Google Slides" to "com.google.android.apps.docs.editors.slides",
                    "Google-Slides" to "com.google.android.apps.docs.editors.slides",
                    "GoogleTasks" to "com.google.android.apps.tasks",
                    "Google Tasks" to "com.google.android.apps.tasks",
                    "Google-Tasks" to "com.google.android.apps.tasks",
                    "YouTube" to "com.google.android.youtube",
                    "youtube" to "com.youtube.android",
                    
                    // ===== 国际应用 =====
                    "Bluecoins" to "com.rammigsoftware.bluecoins",
                    "bluecoins" to "com.rammigsoftware.bluecoins",
                    "Broccoli" to "com.flauschcode.broccoli",
                    "broccoli" to "com.flauschcode.broccoli",
                    "Booking.com" to "com.booking",
                    "Booking" to "com.booking",
                    "booking.com" to "com.booking",
                    "booking" to "com.booking",
                    "BOOKING.COM" to "com.booking",
                    "Duolingo" to "com.duolingo",
                    "duolingo" to "com.duolingo",
                    "Expedia" to "com.expedia.bookings",
                    "expedia" to "com.expedia.bookings",
                    "Joplin" to "net.cozic.joplin",
                    "joplin" to "net.cozic.joplin",
                    "McDonald" to "com.mcdonalds.app",
                    "mcdonald" to "com.mcdonalds.app",
                    "Osmand" to "net.osmand",
                    "osmand" to "net.osmand",
                    "PiMusicPlayer" to "com.Project100Pi.themusicplayer",
                    "pimusicplayer" to "com.Project100Pi.themusicplayer",
                    "Quora" to "com.quora.android",
                    "quora" to "com.quora.android",
                    "Reddit" to "com.reddit.frontpage",
                    "reddit" to "com.reddit.frontpage",
                    "RetroMusic" to "code.name.monkey.retromusic",
                    "retromusic" to "code.name.monkey.retromusic",
                    "SimpleCalendarPro" to "com.scientificcalculatorplus.simplecalculator.basiccalculator.mathcalc",
                    "SimpleSMSMessenger" to "com.simplemobiletools.smsmessenger",
                    "Telegram" to "org.telegram.messenger",
                    "telegram" to "org.telegram.messenger",
                    "temu" to "com.einnovation.temu",
                    "Temu" to "com.einnovation.temu",
                    "Tiktok" to "com.zhiliaoapp.musically",
                    "tiktok" to "com.zhiliaoapp.musically",
                    "Twitter" to "com.twitter.android",
                    "twitter" to "com.twitter.android",
                    "X" to "com.twitter.android",
                    "VLC" to "org.videolan.vlc",
                    "vlc" to "org.videolan.vlc",
                    "WeChat" to "com.tencent.mm",
                    "wechat" to "com.tencent.mm",
                    "Whatsapp" to "com.whatsapp",
                    "WhatsApp" to "com.whatsapp",
                    "whatsapp" to "com.whatsapp",
                    "Facebook" to "com.facebook.katana",
                    "facebook" to "com.facebook.katana",
                    "Instagram" to "com.instagram.android",
                    "instagram" to "com.instagram.android",
                    "Discord" to "com.discord",
                    "discord" to "com.discord",
                    "Zoom" to "us.zoom.videomeetings",
                    "zoom" to "us.zoom.videomeetings",
                    "Skype" to "com.skype.raider",
                    "skype" to "com.skype.raider",
                    "Snapchat" to "com.snapchat.android",
                    "snapchat" to "com.snapchat.android",
                    "Pinterest" to "com.pinterest",
                    "pinterest" to "com.pinterest",
                    "LinkedIn" to "com.linkedin.android",
                    "linkedin" to "com.linkedin.android",
                    "Uber" to "com.ubercab",
                    "uber" to "com.ubercab",
                    "Lyft" to "com.lyft",
                    "lyft" to "com.lyft",
                    "PayPal" to "com.paypal.android.p2pmobile",
                    "paypal" to "com.paypal.android.p2pmobile",
                    "Amazon" to "com.amazon.mshop.android.shopping",
                    "amazon" to "com.amazon.mshop.android.shopping",
                    "eBay" to "com.ebay.mobile",
                    "ebay" to "com.ebay.mobile",
                    "Netflix" to "com.netflix.mediaclient",
                    "netflix" to "com.netflix.mediaclient",
                    "Spotify" to "com.spotify.music",
                    "spotify" to "com.spotify.music",
                    "Airbnb" to "com.airbnb.android",
                    "airbnb" to "com.airbnb.android",
                    "Google-Calendar" to "com.google.android.calendar",
                    "Google Calendar" to "com.google.android.calendar",
                    "google-calendar" to "com.google.android.calendar",
                    "google calendar" to "com.google.android.calendar",
                    "GoogleChat" to "com.google.android.apps.dynamite",
                    "Google Chat" to "com.google.android.apps.dynamite",
                    "Google-Chat" to "com.google.android.apps.dynamite",
                    "GoogleClock" to "com.google.android.deskclock",
                    "Google Clock" to "com.google.android.deskclock",
                    "Google-Clock" to "com.google.android.deskclock",
                    "GoogleContacts" to "com.google.android.contacts",
                    "Google-Contacts" to "com.google.android.contacts",
                    "Google Contacts" to "com.google.android.contacts",
                    "google-contacts" to "com.google.android.contacts",
                    "google contacts" to "com.google.android.contacts",
                    "GoogleDocs" to "com.google.android.apps.docs.editors.docs",
                    "Google Docs" to "com.google.android.apps.docs.editors.docs",
                    "googledocs" to "com.google.android.apps.docs.editors.docs",
                    "google docs" to "com.google.android.apps.docs.editors.docs",
                    "Google Drive" to "com.google.android.apps.docs",
                    "Google-Drive" to "com.google.android.apps.docs",
                    "google drive" to "com.google.android.apps.docs",
                    "google-drive" to "com.google.android.apps.docs",
                    "GoogleDrive" to "com.google.android.apps.docs",
                    "Googledrive" to "com.google.android.apps.docs",
                    "googledrive" to "com.google.android.apps.docs",
                    "GoogleFit" to "com.google.android.apps.fitness",
                    "googlefit" to "com.google.android.apps.fitness",
                    "GoogleKeep" to "com.google.android.keep",
                    "googlekeep" to "com.google.android.keep",
                    "GoogleMaps" to "com.google.android.apps.maps",
                    "Google Maps" to "com.google.android.apps.maps",
                    "googlemaps" to "com.google.android.apps.maps",
                    "google maps" to "com.google.android.apps.maps",
                    "Google Play Books" to "com.google.android.apps.books",
                    "Google-Play-Books" to "com.google.android.apps.books",
                    "google play books" to "com.google.android.apps.books",
                    "google-play-books" to "com.google.android.apps.books",
                    "GooglePlayBooks" to "com.google.android.apps.books",
                    "googleplaybooks" to "com.google.android.apps.books",
                    "GooglePlayStore" to "com.android.vending",
                    "Google Play Store" to "com.android.vending",
                    "Google-Play-Store" to "com.android.vending",
                    "GoogleSlides" to "com.google.android.apps.docs.editors.slides",
                    "Google Slides" to "com.google.android.apps.docs.editors.slides",
                    "Google-Slides" to "com.google.android.apps.docs.editors.slides",
                    "GoogleTasks" to "com.google.android.apps.tasks",
                    "Google Tasks" to "com.google.android.apps.tasks",
                    "Google-Tasks" to "com.google.android.apps.tasks",
                    "Joplin" to "net.cozic.joplin",
                    "joplin" to "net.cozic.joplin",
                    "McDonald" to "com.mcdonalds.app",
                    "mcdonald" to "com.mcdonalds.app",
                    "Osmand" to "net.osmand",
                    "osmand" to "net.osmand",
                    "PiMusicPlayer" to "com.Project100Pi.themusicplayer",
                    "pimusicplayer" to "com.Project100Pi.themusicplayer",
                    "Quora" to "com.quora.android",
                    "quora" to "com.quora.android",
                    "Reddit" to "com.reddit.frontpage",
                    "reddit" to "com.reddit.frontpage",
                    "RetroMusic" to "code.name.monkey.retromusic",
                    "retromusic" to "code.name.monkey.retromusic",
                    "SimpleCalendarPro" to
                            "com.scientificcalculatorplus.simplecalculator.basiccalculator.mathcalc",
                    "SimpleSMSMessenger" to "com.simplemobiletools.smsmessenger",
                    "Telegram" to "org.telegram.messenger",
                    "temu" to "com.einnovation.temu",
                    "Temu" to "com.einnovation.temu",
                    "Tiktok" to "com.zhiliaoapp.musically",
                    "tiktok" to "com.zhiliaoapp.musically",
                    "Twitter" to "com.twitter.android",
                    "twitter" to "com.twitter.android",
                    "X" to "com.twitter.android",
                    "VLC" to "org.videolan.vlc",
                    "WeChat" to "com.tencent.mm",
                    "wechat" to "com.tencent.mm",
                    "Whatsapp" to "com.whatsapp",
                    "WhatsApp" to "com.whatsapp",
            )

    private val normalized: Map<String, String> =
            raw.entries.associate { normalize(it.key) to it.value }

    data class Match(
            val appLabel: String,
            val packageName: String,
            val start: Int,
            val end: Int,
    )

    fun resolve(appName: String): String? {
        val key = normalize(appName)
        if (key.isBlank()) return null
        return normalized[key]
    }

    fun bestMatchInText(text: String): Match? {
        val t = text
        if (t.isBlank()) return null

        var best: Match? = null
        for ((label, pkg) in raw) {
            if (label.isBlank()) continue
            val idx = t.indexOf(label, ignoreCase = true)
            if (idx < 0) continue
            val candidate = Match(label, pkg, idx, idx + label.length)
            val cur = best
            best =
                    when {
                        cur == null -> candidate
                        candidate.start < cur.start -> candidate
                        candidate.start == cur.start && (candidate.end - candidate.start) >
                                (cur.end - cur.start) -> candidate
                        else -> cur
                    }
        }
        return best
    }
}
